const nodemailer = require('nodemailer');

// Create the nodemailer transporter in the module
let transporter = nodemailer.createTransport({
    service: 'gmail',
    auth: {
        user: 'hrvertica@gmail.com', // Your Gmail address
        pass: 'uqcl zccw hdnf mlgm',    // The 16-character App Password generated by Google
    },
});

// Define the sendAttachment function
async function sendAttachment(pdfBuffer, mailTo) {
    try {
        // Email options with PDF buffer as an attachment
        let mailOptions = {
            from: '"0GRA Official" <hrvertica@gmail.com>',
            to: mailTo,
            subject: 'CPI Information from authority',
            text: 'Please find attached the required document',
            attachments: [
                {
                    filename: '0gra_official.pdf',
                    content: pdfBuffer, // Attach the provided buffer
                    contentType: 'application/pdf',
                },
            ],
        };

        // Send the email
        let info = await transporter.sendMail(mailOptions);
        console.log('Email sent:', info.response);
    } catch (error) {
        console.error('Error sending email:', error);
    }
}

// Export the function so it can be used elsewhere
module.exports = { sendAttachment };
