const nodemailer = require('nodemailer');

// Set up the transporter using the App Password
let transporter = nodemailer.createTransport({
    service: 'gmail',
    auth: {
        user: 'hrvertica@gmail.com', // Your Gmail address
        pass: 'uqcl zccw hdnf mlgm',    // The 16-character App Password generated by Google
    },
});

// Example email options
let mailOptions = {
    from: '"OGRA Official" <hrvertica@gmail.com>',
    to: 'mughal@gmail.com',
    subject: 'CPI Information from authority',
    text: 'Please find attached the required document',
};

// Send the email
transporter.sendMail(mailOptions, function (error, info) {
    if (error) {
        console.log('Error:', error);
    } else {
        console.log('Email sent:', info.response);
    }
});
